[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "python-multipart>=0.0.12",
    "s3fs>=2024.9.0",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
]
